# Server
server.port=8081

# Application
spring.application.name=worker-service

# Database
spring.datasource.url=jdbc:mysql://mysql:3306/smartdocflow
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}

spring.redis.host=redis
spring.redis.port=6379

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=60000ms


# Jackson Configuration (important for JSON handling)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

# Mail Configuration (for email actions)
# Mail Configuration
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Service URLs
ai.service.url=${AI_SERVICE_URL}
config.service.url=${CONFIG_SERVICE_URL}

# Logging
logging.level.com.smartdocflow=DEBUG
logging.level.org.springframework.web=INFO



async.executor.core-pool-size=8
async.executor.max-pool-size=32
async.executor.queue-capacity=100


