# Server
server.port=8082

# Application
spring.application.name=ai-service

# File Upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.com.smartdocflow=DEBUG
logging.level.org.springframework.web=INFO
logging.level.net.sourceforge.tess4j=INFO



#MinIO Configuration
minio.url=${MINIO_URL}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}
minio.bucket-name=${MINIO_BUCKET}

logging.level.org.apache.fontbox=ERROR
logging.level.org.apache.pdfbox.pdmodel.font=ERROR